"""통합 대시보드의 설정과 공용 상수를 정의한다."""

from __future__ import annotations

from robot_tests.robot_motion_data import HOME_JOINT

TRAY_LABELS = ("A", "B", "C", "D")

INITIAL_SOIL_STATUS = "미측정"

NEXT_ACTION_MEASURE = "토양 측정"
NEXT_ACTION_ADD_SOIL = "흙추가"
NEXT_ACTION_REMOVE_SOIL = "흙제거"
NEXT_ACTION_REMOVE_ROCK = "돌제거"
NEXT_ACTION_FLATTEN = "평탄화"
NEXT_ACTION_PLANT = "식물 심기"
NEXT_ACTION_DONE = "완료"
NEXT_BUTTON_DEFAULT_TEXT = "다음 작업"

WORK_PHASE_IDLE = "IDLE"
WORK_PHASE_AFTER_CORRECTION = "AFTER_CORRECTION"
WORK_PHASE_DONE = "DONE"

SOIL_STATUS_UNKNOWN = "미측정"
SOIL_STATUS_LOW = "흙부족"
SOIL_STATUS_OK = "정상"
SOIL_STATUS_HIGH = "흙많음"
SOIL_STATUS_OBSTACLE = "장애물감지"
SOIL_STATUS_FAILED = "측정실패"

TOOL_STATE_NONE = "NONE"
TOOL_STATE_PRESS = "PRESS_PLATE_HELD"
TOOL_STATE_SHOVEL = "SHOVEL_HELD"
TOOL_STATE_UNKNOWN = "UNKNOWN"
TOOL_STATE_PRESS_PICKING_APPROACH = "PRESS_PICKING_APPROACH"
TOOL_STATE_PRESS_PICKING_GRIP = "PRESS_PICKING_GRIP"
TOOL_STATE_PRESS_PUTTING_APPROACH = "PRESS_PUTTING_APPROACH"
TOOL_STATE_PRESS_PUTTING_RELEASE = "PRESS_PUTTING_RELEASE"
TOOL_STATE_SHOVEL_PICKING_APPROACH = "SHOVEL_PICKING_APPROACH"
TOOL_STATE_SHOVEL_PICKING_GRIP = "SHOVEL_PICKING_GRIP"
TOOL_STATE_SHOVEL_PUTTING_APPROACH = "SHOVEL_PUTTING_APPROACH"
TOOL_STATE_SHOVEL_PUTTING_RELEASE = "SHOVEL_PUTTING_RELEASE"

TOOL_TRANSITION_STATES = {
    TOOL_STATE_PRESS_PICKING_APPROACH,
    TOOL_STATE_PRESS_PICKING_GRIP,
    TOOL_STATE_PRESS_PUTTING_APPROACH,
    TOOL_STATE_PRESS_PUTTING_RELEASE,
    TOOL_STATE_SHOVEL_PICKING_APPROACH,
    TOOL_STATE_SHOVEL_PICKING_GRIP,
    TOOL_STATE_SHOVEL_PUTTING_APPROACH,
    TOOL_STATE_SHOVEL_PUTTING_RELEASE,
}

HOME_POSE = list(HOME_JOINT)

WORKSPACE_SETUP_PATH = "/home/rokey/ws_cobot_pjt/ws_cobot1/install/setup.bash"

# 실제 연결 해제 이벤트와 로봇 상태 heartbeat를 함께 사용한다. 일시적인 메시지
# 누락은 무시하고, 재연결은 여러 메시지를 연속 수신한 뒤 확정한다.
ROBOT_JOINT_STATE_TOPIC = "/dsr01/joint_states"
ROBOT_DISCONNECTION_TOPIC = "/dsr01/robot_disconnection"
ROBOT_ERROR_TOPIC = "/dsr01/error"
ROBOT_STATE_SERVICE = "/dsr01/system/get_robot_state"
ROBOT_CONTROL_SERVICE = "/dsr01/system/set_robot_control"
ROBOT_HEARTBEAT_TIMEOUT_SECONDS = 5.0
ROBOT_RECONNECT_MESSAGE_COUNT = 3
ROBOT_STATE_POLL_INTERVAL_SECONDS = 0.5
ROBOT_STATE_REQUEST_TIMEOUT_SECONDS = 2.0

# 현장 확인값: 물리 안전복구 완료=1, SAFE_OFF=3, 물리 비상정지=6.
# /dsr01/system/get_robot_state 응답을 기준으로 판정한다.
ROBOT_STATE_STANDBY = 1
ROBOT_STATE_SAFE_OFF = 3
ROBOT_STATE_EMERGENCY_STOP = 6
ROBOT_RECOVERY_READY_STATES = (ROBOT_STATE_STANDBY, ROBOT_STATE_SAFE_OFF)
ROBOT_CONTROL_RESET_SAFE_OFF = 3
ROBOT_RECOVERY_CONFIRM_TIMEOUT_MS = 8000

UI_PATH_CANDIDATES = (
    "/home/rokey/ws_cobot_pjt/ws_cobot1/src/robot_tests/robot_tests/integrated/smartfarm_dashboard.ui",
)

INTER_NODE_DELAY_MS = 1000
PRESS_PICKUP_HANDOFF_DELAY_MS = 500
PRESS_PUTDOWN_HANDOFF_DELAY_MS = 500

MEASURE_NODE = "integrated_tray_soil_state_check_node"
HOME_NODE = "go_home_test"
INTEGRATED_FLATTEN_NODE = "integrated_tray_soil_flatten_node"
INTEGRATED_NEXT_STEP_NODE = "integrated_tray_next_step_node"
INTEGRATED_MANUAL_NODE = "integrated_manual_control_node"
INTEGRATED_ESTOP_NODE = "integrated_emergency_stop_node"
INTEGRATED_TOOL_NODE = "integrated_tool_control_node"

TRAY_TO_PLANT_INDEX = {
    "A": 1,
    "B": 2,
    "C": 3,
    "D": 4,
}
